### ISSUE TITLE
原谅我连用都不会用

### ISSUE THREAD

**Issue by Linhieng** [HomeArchbishop/picable#5]
本地 server 后，注册后登陆一直提示登录过期。。。。😣😣

**Comment by Linhieng** [comment]
401鉴权错误

**Comment by Linhieng** [comment]
没事了，没学过 electron，用点击哪个开始运行都不知道🤣🤣🤣，用了electron;build 后重新注册了一下，再登陆就ok了。原来这个哔咔，真的是那个哔咔呀，666，🤣🤣🤣

**Comment by HomeArchbishop** [comment]
哈哈哈哈，就是用的那个哔咔的服务写的啊🤣🤣🤣
